### ISSUE TITLE
No documentation for the parameters tuning

### ISSUE THREAD

**Issue by deepak-anzo** [mich1342/ros2_laser_scan_merger#12]
Please add documentation to tune the parameters.

**Comment by mich1342** [comment]
Hi @deepak-anzo,

Thank you for your interest in the repo. Will try to add some docs on my free time this weekend.

**Comment by deepak-anzo** [comment]
Thanks, @mich1342 .

**Comment by mich1342** [comment]
Done adding some parameters

**Comment by maksimmasalski** [comment]
Where to find those docs? It is still not clear how to tune parameters...

**Comment by mich1342** [comment]
Hi @maksimmasalski ,

I believe the docs in the readme is clear enough to describe all of the parameters to tune the offset / position of each lidar.
